theme: jekyll-theme-minimal

defaults:
  -
    scope:
      path: "/_layouts/post.html" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
